<h2 dir=rtl>
مرور
</h2>

<div dir=rtl>
    <b>سوال:</b>
با استفاده از اعداد تصادفی عدد پی را تخمین بزنید.
</div>

<div dir=rtl>
<b>پاسخ:</b>
    ابتدا لازم است که با اعداد تصادفی آشنا شویم.
</div>

In [1]:
import numpy as np

In [2]:
np.random.rand(2, 3)

array([[0.83614487, 0.01379773, 0.17988455],
       [0.42502816, 0.21644981, 0.32687251]])

In [3]:
np.random.randn(2, 3)

array([[ 1.17958645, -0.76929463,  0.41231559],
       [ 0.19754894, -0.69061039,  0.9206211 ]])

In [4]:
np.random.uniform(1, 5, (2, 3))

array([[1.92985757, 1.67278487, 3.15904974],
       [1.15715402, 2.56936533, 4.59798619]])

<div dir=rtl>
برای حل مسئله یاد‌شده، ۱۰۰۰۰۰۰ نقطه تصادفی محدود به مربعی به مساحت یک تولید می‌کنیم. نسبتی از نقاط که در ربع دایره محاط در مربع قرار می‌گیرند برابر است با نسبت مساحت آن ربع دایره.
به عبارت دیگر این نسبت برابر است با
    $\frac{\pi}{4}$.
</div>

In [5]:
total_numbers = 1000000
count = 0
xpoints = np.random.rand(total_numbers)
ypoints = np.random.rand(total_numbers)
for x, y in zip(xpoints, ypoints):
    if (x ** 2 + y ** 2) <= 1:
        count += 1
print(f"PI is approximately {4 * (count/total_numbers):.2f}")

PI is approximately 3.14
